--- 
title: "Data Wrangling for Economists"
author: 
  - Michael Topper^[UC Santa Barbara, michaeltopper@ucsb.edu]
  - Danny Klinenberg^[UC Santa Barbara, dklinenberg@ucsb.edu]
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: openscapes/series
description: "Enter description."
---

# Welcome {#welcome}

This book is designed to go with the UCSB course Econ 245: Data Wrangling for Economists. The book is still a work in progress and will be updated regularly.

In the following chapters, you will practice data wrangling with some hand-holding as well as some simple exercises to check your understanding. The purpose of these chapters is the following:

1. Make your homework easier.
2. Make you a better coder by observing good code.
3. Get hands-on practice with functions you will need to complete your assignments.
4. Provide a reference for each topic in the course.


It is *strongly* suggested that you code along with the examples that we go through, although there will be times when copying and pasting can be useful (e.g., loading in a data set). 

## Organization

The book's organization was designed to help the second-year PhD student get ready to do research as soon as possible. There is focus on both organization and coding techniques. In later updates, we hope to add in some more advanced topics that are covered in the course such as PDF extracting, webscraping, estimation, making a package, publication tables, and spatial data. The book was made with a `tidyverse` focus.